apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rhtap-buildpack-demo-1-xidx
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cmoullia-tenant/rhtap-buildpack-demo-1-1/rhtap-buildpack-demo-1-xidx@sha256:aebd6521410cec783b8073e7ed525718d0ead714cf86444be9189dcc9f2bb71b
        name: my-java-quarkus
        resources: {}
status: {}
