apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: rhtap-buildpack-demo-1-xidx
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: rhtap-buildpack-demo-1-xidx
    app.kubernetes.io/part-of: rhtap-buildpack-demo-1-1
  name: rhtap-buildpack-demo-1-xidx
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: rhtap-buildpack-demo-1-xidx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: rhtap-buildpack-demo-1-xidx
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/cmoullia-tenant/rhtap-buildpack-demo-1-1/rhtap-buildpack-demo-1-xidx@sha256:aebd6521410cec783b8073e7ed525718d0ead714cf86444be9189dcc9f2bb71b
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
